export default {
  name: 'club',
  title: 'Configuració del Club',
  type: 'document',
  __experimental_actions: ['update', 'publish'],
  fields: [
    { name: 'name', title: 'Nom', type: 'string' },
    { name: 'shortName', title: 'Nom curt', type: 'string' },
    { name: 'founded', title: 'Any fundació', type: 'number' },
    { name: 'competition', title: 'Competició', type: 'string' },
    { name: 'group', title: 'Grup', type: 'string' },
    { name: 'season', title: 'Temporada', type: 'string' },
    { name: 'coach', title: 'Entrenador', type: 'string' },
    { name: 'badge', title: 'Escut', type: 'image' },
    { name: 'stadiumName', title: 'Nom estadi', type: 'string' },
    { name: 'stadiumCapacity', title: 'Capacitat', type: 'number' },
    { name: 'stadiumCity', title: 'Ciutat', type: 'string' },
    { name: 'heroStadium', title: 'Foto hero estadi', type: 'image' },
    { name: 'heroAficio', title: 'Foto hero afició', type: 'image' },
  ],
  preview: { select: { title: 'name', subtitle: 'season' } },
};
