export default {
  name: 'standing',
  title: 'Classificació',
  type: 'document',
  fields: [
    { name: 'pos', title: 'Posició', type: 'number' },
    { name: 'team', title: 'Equip', type: 'string' },
    { name: 'shortName', title: 'Abreviatura', type: 'string' },
    { name: 'badge', title: 'Escut', type: 'image' },
    { name: 'played', title: 'PJ', type: 'number' },
    { name: 'won', title: 'V', type: 'number' },
    { name: 'drawn', title: 'E', type: 'number' },
    { name: 'lost', title: 'D', type: 'number' },
    { name: 'gf', title: 'GF', type: 'number' },
    { name: 'ga', title: 'GC', type: 'number' },
    { name: 'points', title: 'Punts', type: 'number' },
  ],
  orderings: [{ title: 'Posició', name: 'posAsc', by: [{ field: 'pos', direction: 'asc' }] }],
  preview: { select: { title: 'team', subtitle: 'pos' } },
};
